name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  test-build:
    name: Test Build
    runs-on: alt-sisyphus

    steps:
      - name: Install libs on container
        run: |
          apt-get update
          apt-get install -y gettext-tools meson vala blueprint-compiler "pkgconfig(libadwaita-1)" "pkgconfig(gee-0.8)" "pkgconfig(libpeas-2)" "pkgconfig(json-glib-1.0)" "gir(Peas)=2" "gir(Gee)=0.8" "gir(Adw)=1" gobject-introspection-devel

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        run: meson setup build

      - name: Compile
        run: meson compile -C build

      - name: Test
        run: meson test -C build
