name: Docs

on:
  push:
    workflow_dispatch:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            valac \
            valadoc \
            libgee-0.8-dev \
            libadwaita-1-dev \
            libgirepository-1.0-dev \
            gettext \
            git \
            python3-pip \
            desktop-file-utils \

      - name: Install meson
        run: |
          sudo pip3 install --break-system-packages meson

      - name: Install blueprint compiler
        run: |
          git clone https://gitlab.gnome.org/GNOME/blueprint-compiler.git
          cd blueprint-compiler
          meson setup --prefix=/usr build
          sudo ninja install -C build

      - name: Install libpeas
        run: |
          git clone --depth 1 --branch 2.0.7 https://gitlab.gnome.org/GNOME/libpeas.git
          cd libpeas
          meson setup --prefix=/usr -Dvapi=true -Dgjs=false -Dlua51=false -Dpython3=false build
          sudo ninja install -C build

      - name: Configure build
        run: |
          meson setup _build -Ddocs=true --prefix=$PWD/_install

      - name: Compile documentation
        run: |
          meson compile -C _build

      - name: Install documentation
        run: |
          meson install -C _build

      - name: Prepare artifacts
        run: |
          mkdir -p public/
          cp -r _install/share/doc/*/valadoc/* public/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    needs: build-docs
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
